{% set name = "django-rq" %}
{% set version = "1.3.1" %}
{% set sha256 = "858636b52b470f9a5e5ebc721ba5d9383dfcb649c46a8dcae20fe2b2670cfac6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - rq >=0.5.5

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(INSTALLED_APPS=['django_rq'], RQ_QUEUES={}); django.setup(); import django_rq"    

about:
  home: https://github.com/ui/django-rq
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A simple app that provides django integration for RQ (Redis Queue)'
  description: |
    Django integration with RQ, a Redis based Python queuing library. Django-RQ 
    is a simple app that allows you to configure your queues in django's settings.py 
    and easily use them in your project.
  doc_url: https://github.com/ui/django-rq
  dev_url: https://github.com/ui/django-rq

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
